server:
  port: 8069
spring:
  application:
    name: CONFIG-SERVICE

  cloud:
    config:
      server:
        git:
          uri: https://github.com/OnlyAdi29/microservice-configuration
          clone-on-start: true

